---
- name: Install Filebeat 5.6
  apt:
    deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.0-amd64.deb
  when: "'Filebeat-release' in group_names"

- name: Configure Filebeat 5.6 to send Icinga logs
  template:
     src: templates/filebeat-rel.yml.j2
     dest: /etc/filebeat/filebeat.yml
  notify:
     - restart filebeat
  when: "'Filebeat-release' in group_names"
...
